### ISSUE TITLE
Strapi: Error when building from workspace root

### ISSUE THREAD

**Issue by certainlyakey** [TriPSs/nx-extend#176]
Hi, thanks a lot for the great software! 
I noticed that when i run `npx nx run <package-name>:build` in the workspace root, i get an error:

```
Package subpath './dist/commands/builders/admin' is not defined by "exports" in <workspace-root>/node_modules/@strapi/strapi/package.json
```

Here's a repro using the latest nx: https://github.com/certainlyakey/nx-extendstrapi-repro/. However, the same error (just with  `./dist/commands/builders`) appears for me even when downgrading to @nx-extend/strapi 6.1.8 and nx 16. 

The build command works fine when run in the package folder as `npm run build` (although on first launch it asks twice to install the admin dependencies).

**Comment by TriPSs** [comment]
Hi, can you make sure you use the latest `@nx-extend/strapi` with the latest Strapi? (Version 7.0.0 of `@nx-extend/strapi` had this issue, which was fixed in 7.0.1)

Thanks for the repo but I don't see any Strapi projects?

**Comment by certainlyakey** [comment]
Hey, sorry forgot to add a commit with it 🤦‍♀️. Now it's there. The example repo should use 7.0.1.

**Comment by TriPSs** [comment]
I see the issue, Strapi complelty changed their [build pipeline](https://github.com/strapi/strapi/pull/18539) which is now causing issues. If you dowgrade strapi to `"4.15.0"` it should work again until we update the build generator in @nx-extend.

**Comment by certainlyakey** [comment]
Alright, thanks for letting me know, I will try to downgrade Strapi then and see if that works.

**Comment by certainlyakey** [comment]
Downgraded Strapi and related plugin packages to "4.15.0" (strict dependency) in the example project and my real project - it's unfortunately still the same `Package subpath './dist/commands/builders/admin' is not defined by "exports"` error.
